plugins {
    id 'java-library'
    id 'io.spring.dependency-management' version '1.1.5'
}

group = 'com.icms'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:4.1.1'
    }
}

dependencies {
    // Spring Data JPA (para MappedSuperclass, JPA Annotations y Auditing)
    compileOnly 'org.springframework.boot:spring-boot-starter-data-jpa'
    
    // Spring Web (para DTOs, RestControllerAnnotations y LocaleContextHolder)
    compileOnly 'org.springframework.boot:spring-boot-starter-web'
    
    // Spring Security (para extracción del usuario autenticado en AuditorAware)
    compileOnly 'org.springframework.boot:spring-boot-starter-security'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Jackson para serialización JSON
    implementation 'com.fasterxml.jackson.core:jackson-databind'
}