[versions]
java = "24"
springBoot = "4.1.1" # Spring Boot version 4.1.1  3.4.0
dependencyManagement = "1.1.7"
liquibase = "2.2.2"
mapstruct = "1.6.3"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
dependency-management = {id = "io.spring.dependency-management", version.ref = "dependencyManagement"}
liquibase = {id = "org.liquibase.gradle", version.ref = "liquibase"}

[libraries]
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }
dependency-management-gradle-plugin = { module = "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin", version.ref = "dependencyManagement" }
liquibase-gradle-plugin = { module = "org.liquibase.gradle:org.liquibase.gradle.gradle.plugin", version.ref = "liquibase" }
mapstruct = {module = "org.mapstruct:mapstruct", version.ref = "mapstruct"}