server:
  port: ${PORT_GATEWAY}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
          # Definición de Rutas hacia los Microservicios
          routes:
            - id: servicio-autenticacion-usuarios
              uri: http://user-auth:${PORT_USER_AUTH}
              predicates:
                - Path=/api/v1/auth/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: DEBUG