server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Configuración de CORS para permitir peticiones desde el Frontend o Postman
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      
      # Definición de Rutas hacia los Microservicios
      routes:
        # Ruta 1: Servicio de Autenticación y Usuarios
        - id: servicio-autenticacion-usuarios
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: DEBUG