plugins {
    id 'spring-jpa-conventions'
    id 'migration-conventions'
}

group = 'com.icms'
version = '0.0.1-SNAPSHOT'

configurations {
    mockitoAgent
}

dependencies {
	// Módulo local del mismo proyecto Gradle; no es necesario declararlo como dependencia publicada.
	implementation project(':shared-kernel')
	implementation libs.spring.boot.starter.security
	implementation libs.spring.boot.starter.webmvc

	testImplementation libs.spring.boot.starter.security.test
	testImplementation libs.spring.boot.starter.webmvc.test
	testImplementation libs.spring.boot.test.autoconfigure
	testImplementation libs.mockito.core
	testImplementation libs.instancio.junit

	testRuntimeOnly libs.junit.platform

	// Requerido por la tarea de Liquibase para ejecutar desde CLI postgre
    liquibaseRuntime libs.postgresql

	mockitoAgent(libs.mockito.core) { transitive = false }
}

// Configuración de la base de datos EXCLUSIVA de este microservicio
liquibase {
    activities {
        main {
            changelogFile 'user-auth/src/main/resources/db/migration-root.yaml'
            
            // Toma la propiedad por CLI (-PdbUrl=...) o usa la BD por defecto de este servicio
            url project.hasProperty('dbUrl') ? project.property('dbUrl') : 'jdbc:postgresql://localhost:25432/ICMS_UA'
            username project.hasProperty('dbUser') ? project.property('dbUser') : 'postgres'
            password project.hasProperty('dbPassword') ? project.property('dbPassword') : 'adm123456'
        }
    }
}
/** Configuración de pruebas con JUnit y Mockito */
/**tasks.named('test', Test) {
    useJUnitPlatform()
    jvmArgs "-javaagent:${configurations.mockitoAgent.singleFile}"
}*/
