spring:
  application:
    name: user-auth
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:25432}/${DB_USER_AUTH_NAME:ICMS_UA}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:adm123456}
  liquibase:
    change-log: classpath:db/migration-root.yaml
    enabled: ${LIQUIBASE_ENABLED:false}  
  jpa:
    hibernate:
      # En desarrollo, 'validate' asegura que Liquibase hizo bien su trabajo [10, 11]
      ddl-auto: validate 
      dialect: org.hibernate.dialect.PostgreSQLDialect
      physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      envers:
        audit_table_suffix: _aud
        revision_field_name: rev
        revision_type_field_name: revtype
        store_data_at_delete: true
  # Configuración de Spring MVC, this includes settings for handling web requests and responses which means you can customize how your application handles HTTP requests and responses.
  mvc:
    problem:
      include-stacktrace: always # Always include stacktrace in the response for debugging purposes

server:
  port: ${PORT_USER_AUTH:8081}


---
spring:
  config:
    activate:
      on-profile: test

  liquibase:
    enabled: false

  session:
    store-type: none
    
  cache:
    type: none
