services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${PORT_GATEWAY_PUBLIC}:${PORT_GATEWAY}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - PORT_GATEWAY=${PORT_GATEWAY}
      - LIQUIBASE_ENABLED=${LIQUIBASE_ENABLED}
      - PORT_USER_AUTH=${PORT_USER_AUTH}
      - HOST_USER_AUTH=${HOST_USER_AUTH}
    networks:
      - e-commerce-network

  user-auth:
    build:
      context: ../user-auth
      dockerfile: Dockerfile
    container_name: user-auth
    ports:
      - "${PORT_USER_AUTH}:${PORT_USER_AUTH}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_USER_AUTH_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - LIQUIBASE_ENABLED=${LIQUIBASE_ENABLED}
      - PORT_USER_AUTH=${PORT_USER_AUTH}
    networks:
      - e-commerce-network
      - docker_db_network

networks:
  e-commerce-network:
    driver: bridge
  docker_db_network:
    external: true